# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_ui_files/dbms.ui'
#
# Created: Tue Nov 17 00:03:07 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setWindowModality(QtCore.Qt.ApplicationModal)
        TabWidget.resize(499, 338)
        TabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        TabWidget.setSizeIncrement(QtCore.QSize(408, 335))
        self.basicUsage_tab = QtGui.QWidget()
        self.basicUsage_tab.setObjectName("basicUsage_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.basicUsage_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.upload_label = QtGui.QLabel(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_label.sizePolicy().hasHeightForWidth())
        self.upload_label.setSizePolicy(sizePolicy)
        self.upload_label.setObjectName("upload_label")
        self.gridLayout_2.addWidget(self.upload_label, 0, 0, 1, 2)
        self.uploadFile_LineEdit = QtGui.QLineEdit(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadFile_LineEdit.sizePolicy().hasHeightForWidth())
        self.uploadFile_LineEdit.setSizePolicy(sizePolicy)
        self.uploadFile_LineEdit.setObjectName("uploadFile_LineEdit")
        self.gridLayout_2.addWidget(self.uploadFile_LineEdit, 1, 0, 1, 1)
        self.upload_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_pushButton.sizePolicy().hasHeightForWidth())
        self.upload_pushButton.setSizePolicy(sizePolicy)
        self.upload_pushButton.setObjectName("upload_pushButton")
        self.gridLayout_2.addWidget(self.upload_pushButton, 1, 1, 1, 1)
        self.add_to_db_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_to_db_pushButton.sizePolicy().hasHeightForWidth())
        self.add_to_db_pushButton.setSizePolicy(sizePolicy)
        self.add_to_db_pushButton.setObjectName("add_to_db_pushButton")
        self.gridLayout_2.addWidget(self.add_to_db_pushButton, 1, 2, 1, 1)
        self.line = QtGui.QFrame(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 3)
        self.label = QtGui.QLabel(self.basicUsage_tab)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.basicUsage_tab)
        self.label_3.setMaximumSize(QtCore.QSize(281, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.addStudent_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStudent_pushButton.sizePolicy().hasHeightForWidth())
        self.addStudent_pushButton.setSizePolicy(sizePolicy)
        self.addStudent_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addStudent_pushButton.setObjectName("addStudent_pushButton")
        self.gridLayout_2.addWidget(self.addStudent_pushButton, 4, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.basicUsage_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.deleteStudent_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteStudent_pushButton.sizePolicy().hasHeightForWidth())
        self.deleteStudent_pushButton.setSizePolicy(sizePolicy)
        self.deleteStudent_pushButton.setObjectName("deleteStudent_pushButton")
        self.gridLayout_2.addWidget(self.deleteStudent_pushButton, 5, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.basicUsage_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.updateStudent_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateStudent_pushButton.sizePolicy().hasHeightForWidth())
        self.updateStudent_pushButton.setSizePolicy(sizePolicy)
        self.updateStudent_pushButton.setObjectName("updateStudent_pushButton")
        self.gridLayout_2.addWidget(self.updateStudent_pushButton, 6, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.basicUsage_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.examDate_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examDate_pushButton.sizePolicy().hasHeightForWidth())
        self.examDate_pushButton.setSizePolicy(sizePolicy)
        self.examDate_pushButton.setObjectName("examDate_pushButton")
        self.gridLayout_2.addWidget(self.examDate_pushButton, 7, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.basicUsage_tab)
        self.label_2.setMaximumSize(QtCore.QSize(281, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 8, 0, 1, 1)
        self.generate_pushButton = QtGui.QPushButton(self.basicUsage_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_pushButton.sizePolicy().hasHeightForWidth())
        self.generate_pushButton.setSizePolicy(sizePolicy)
        self.generate_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.generate_pushButton.setObjectName("generate_pushButton")
        self.gridLayout_2.addWidget(self.generate_pushButton, 8, 1, 1, 2)
        TabWidget.addTab(self.basicUsage_tab, "")
        self.advancedUsage_tab = QtGui.QWidget()
        self.advancedUsage_tab.setObjectName("advancedUsage_tab")
        self.gridLayout = QtGui.QGridLayout(self.advancedUsage_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtGui.QLabel(self.advancedUsage_tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.view_pushButton = QtGui.QPushButton(self.advancedUsage_tab)
        self.view_pushButton.setObjectName("view_pushButton")
        self.gridLayout.addWidget(self.view_pushButton, 0, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.advancedUsage_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.checkConflict_pushButton = QtGui.QPushButton(self.advancedUsage_tab)
        self.checkConflict_pushButton.setObjectName("checkConflict_pushButton")
        self.gridLayout.addWidget(self.checkConflict_pushButton, 1, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.advancedUsage_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.createDatabase_pushButton = QtGui.QPushButton(self.advancedUsage_tab)
        self.createDatabase_pushButton.setObjectName("createDatabase_pushButton")
        self.gridLayout.addWidget(self.createDatabase_pushButton, 2, 1, 1, 2)
        self.createdB_frame = QtGui.QFrame(self.advancedUsage_tab)
        self.createdB_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.createdB_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.createdB_frame.setObjectName("createdB_frame")
        self.gridLayout_4 = QtGui.QGridLayout(self.createdB_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtGui.QLabel(self.createdB_frame)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 2)
        self.createDB_lineEdit = QtGui.QLineEdit(self.createdB_frame)
        self.createDB_lineEdit.setObjectName("createDB_lineEdit")
        self.gridLayout_4.addWidget(self.createDB_lineEdit, 1, 0, 1, 2)
        self.cancel_pushButton = QtGui.QPushButton(self.createdB_frame)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout_4.addWidget(self.cancel_pushButton, 2, 0, 1, 1)
        self.ok_pushButton = QtGui.QPushButton(self.createdB_frame)
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.gridLayout_4.addWidget(self.ok_pushButton, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.createdB_frame, 3, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.advancedUsage_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.selectDB_comboBox = QtGui.QComboBox(self.advancedUsage_tab)
        self.selectDB_comboBox.setObjectName("selectDB_comboBox")
        self.gridLayout.addWidget(self.selectDB_comboBox, 4, 1, 1, 1)
        self.selectdb_pushButton = QtGui.QPushButton(self.advancedUsage_tab)
        self.selectdb_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectdb_pushButton.setObjectName("selectdb_pushButton")
        self.gridLayout.addWidget(self.selectdb_pushButton, 4, 2, 1, 1)
        TabWidget.addTab(self.advancedUsage_tab, "")
        self.credits_tab = QtGui.QWidget()
        self.credits_tab.setObjectName("credits_tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.credits_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit = QtGui.QTextEdit(self.credits_tab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        TabWidget.addTab(self.credits_tab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.cancel_pushButton, QtCore.SIGNAL("clicked()"), self.createDB_lineEdit.clear)
        QtCore.QObject.connect(self.createDatabase_pushButton, QtCore.SIGNAL("clicked()"), self.createdB_frame.show)
        QtCore.QObject.connect(self.cancel_pushButton, QtCore.SIGNAL("clicked()"), self.createdB_frame.hide)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(QtGui.QApplication.translate("TabWidget", "Practical Time Table Mgmt Portal", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_label.setToolTip(QtGui.QApplication.translate("TabWidget", "The file should be in Comma Separated Value format", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_label.setText(QtGui.QApplication.translate("TabWidget", "Please select a CSV file containing the student information:", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadFile_LineEdit.setToolTip(QtGui.QApplication.translate("TabWidget", "Drag & Drop the student information file", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_pushButton.setText(QtGui.QApplication.translate("TabWidget", "&Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.add_to_db_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Add to DB", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TabWidget", "Usage Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TabWidget", "Add a new Student to the database:", None, QtGui.QApplication.UnicodeUTF8))
        self.addStudent_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TabWidget", "Delete a Student from the database:", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteStudent_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TabWidget", "Update a Student\'s Information:", None, QtGui.QApplication.UnicodeUTF8))
        self.updateStudent_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TabWidget", "Add a new Lab Exam: ", None, QtGui.QApplication.UnicodeUTF8))
        self.examDate_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Exam Dates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TabWidget", "Click Generate to create the time table:", None, QtGui.QApplication.UnicodeUTF8))
        self.generate_pushButton.setText(QtGui.QApplication.translate("TabWidget", "&Generate", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.basicUsage_tab), QtGui.QApplication.translate("TabWidget", "&Basic Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TabWidget", "View the Database Contents:", None, QtGui.QApplication.UnicodeUTF8))
        self.view_pushButton.setText(QtGui.QApplication.translate("TabWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TabWidget", "Two exams on the same day conflict.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkConflict_pushButton.setToolTip(QtGui.QApplication.translate("TabWidget", "Checks if there are any date clashes of student\'s exams", None, QtGui.QApplication.UnicodeUTF8))
        self.checkConflict_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Check &Conflict", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TabWidget", "Create a new time table database.", None, QtGui.QApplication.UnicodeUTF8))
        self.createDatabase_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Create &Databse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TabWidget", "Please Enter the name of the dB", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_pushButton.setText(QtGui.QApplication.translate("TabWidget", "&CANCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_pushButton.setText(QtGui.QApplication.translate("TabWidget", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TabWidget", "Select the Working Database.", None, QtGui.QApplication.UnicodeUTF8))
        self.selectdb_pushButton.setText(QtGui.QApplication.translate("TabWidget", "Select", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.advancedUsage_tab), QtGui.QApplication.translate("TabWidget", "&Advanced Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("TabWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bitstream Vera Sans\'; font-size:8.59961pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:11pt; font-weight:600;\">Practical Exam Time Table </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:11pt; font-weight:600;\">Management Software</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; text-decoration: underline;\">Authors</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt; text-decoration: underline;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:600;\">Lavanya S</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">USN: 1MV07CS050</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Email Id:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:600;\">Kunal Ghosh</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">USN: 1MV07CS048</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Email Id: kunal [dot] t2 [at] gmail [dot] com</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Blog: www.kunalghosh.co.cc</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Website: kunalghosh.net46.net</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; text-decoration: underline;\">Notice</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">This software is distributed under the GPL v2 License.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">To get a copy of the license write to the author.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; color:#ff0000;\">In case you have any comments or suggestions please contact either author</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt; color:#ff0000;\">by email </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.credits_tab), QtGui.QApplication.translate("TabWidget", "Credits", None, QtGui.QApplication.UnicodeUTF8))

