# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_ui_files/View_contents.ui'
#
# Created: Sun Nov  8 22:37:52 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FormReport(object):
    def setupUi(self, FormReport):
        FormReport.setObjectName("FormReport")
        FormReport.resize(841, 586)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormReport.sizePolicy().hasHeightForWidth())
        FormReport.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(FormReport)
        self.gridLayout.setObjectName("gridLayout")
        self.studentDetails_pushButton = QtGui.QPushButton(FormReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentDetails_pushButton.sizePolicy().hasHeightForWidth())
        self.studentDetails_pushButton.setSizePolicy(sizePolicy)
        self.studentDetails_pushButton.setObjectName("studentDetails_pushButton")
        self.gridLayout.addWidget(self.studentDetails_pushButton, 1, 0, 1, 1)
        self.subjects_pushButton = QtGui.QPushButton(FormReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjects_pushButton.sizePolicy().hasHeightForWidth())
        self.subjects_pushButton.setSizePolicy(sizePolicy)
        self.subjects_pushButton.setObjectName("subjects_pushButton")
        self.gridLayout.addWidget(self.subjects_pushButton, 2, 0, 1, 1)
        self.labs_pushButton = QtGui.QPushButton(FormReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labs_pushButton.sizePolicy().hasHeightForWidth())
        self.labs_pushButton.setSizePolicy(sizePolicy)
        self.labs_pushButton.setObjectName("labs_pushButton")
        self.gridLayout.addWidget(self.labs_pushButton, 3, 0, 1, 1)
        self.examDates_pushButton = QtGui.QPushButton(FormReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examDates_pushButton.sizePolicy().hasHeightForWidth())
        self.examDates_pushButton.setSizePolicy(sizePolicy)
        self.examDates_pushButton.setObjectName("examDates_pushButton")
        self.gridLayout.addWidget(self.examDates_pushButton, 4, 0, 1, 1)
        self.viewContents_tableWidget = QtGui.QTableWidget(FormReport)
        self.viewContents_tableWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.viewContents_tableWidget.sizePolicy().hasHeightForWidth())
        self.viewContents_tableWidget.setSizePolicy(sizePolicy)
        self.viewContents_tableWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.viewContents_tableWidget.setAutoFillBackground(False)
        self.viewContents_tableWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.viewContents_tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.viewContents_tableWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.viewContents_tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.viewContents_tableWidget.setObjectName("viewContents_tableWidget")
        self.viewContents_tableWidget.setColumnCount(0)
        self.viewContents_tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.viewContents_tableWidget, 1, 1, 4, 1)
        self.viewContentsMain_label = QtGui.QLabel(FormReport)
        self.viewContentsMain_label.setMinimumSize(QtCore.QSize(0, 30))
        self.viewContentsMain_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.viewContentsMain_label.setFont(font)
        self.viewContentsMain_label.setTextFormat(QtCore.Qt.AutoText)
        self.viewContentsMain_label.setAlignment(QtCore.Qt.AlignCenter)
        self.viewContentsMain_label.setObjectName("viewContentsMain_label")
        self.gridLayout.addWidget(self.viewContentsMain_label, 0, 1, 1, 1)

        self.retranslateUi(FormReport)
        QtCore.QMetaObject.connectSlotsByName(FormReport)

    def retranslateUi(self, FormReport):
        FormReport.setWindowTitle(QtGui.QApplication.translate("FormReport", "Report Window", None, QtGui.QApplication.UnicodeUTF8))
        self.studentDetails_pushButton.setText(QtGui.QApplication.translate("FormReport", "Student\'s Details", None, QtGui.QApplication.UnicodeUTF8))
        self.subjects_pushButton.setText(QtGui.QApplication.translate("FormReport", "Subjects", None, QtGui.QApplication.UnicodeUTF8))
        self.labs_pushButton.setText(QtGui.QApplication.translate("FormReport", "Labs", None, QtGui.QApplication.UnicodeUTF8))
        self.examDates_pushButton.setText(QtGui.QApplication.translate("FormReport", "Exam Dates", None, QtGui.QApplication.UnicodeUTF8))
        self.viewContents_tableWidget.setSortingEnabled(False)

